apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: django-container
          image: your-dockerhub-username/django-messaging-app:latest  # Replace with your actual image
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings
            - name: PYTHONUNBUFFERED
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: messaging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
